In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
X,y=load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=3)

In [6]:
lr=LinearRegression()

In [7]:
lr.fit(X_train,y_train)

LinearRegression()

In [8]:
lr.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [9]:
lr.intercept_

153.13441535285003

In [10]:
y_pred=lr.predict(X_test)

In [11]:
r2_score(y_test,y_pred)

0.4161792211496943

In [26]:
class SGDRegressor:
    def __init__(self,learning_rate=0.01,epochs=100):
        self.coef=None
        self.intercept=None
        self.lr=learning_rate
        self.epochs=epochs
    
    def fit(self,X_train,y_train):
        self.intercept=0
        self.coef=np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx=np.random.randint(0,X_train.shape[0])
                y_hat=np.dot(X_train[idx],self.coef) + self.intercept
                
                intercept_der=-2*(y_train[idx]-y_hat)
                self.intercept=self.intercept - (self.lr*intercept_der)
                
                coef_der=-2* np.dot((y_train[idx] -y_hat),X_train[idx])
                self.coef=self.coef - (self.lr*coef_der)
            print(f"coef={self.coef},intercept={self.intercept}")
        
    def predict(self,X_test):
        return np.dot(X_test,self.coef) + self.intercept

In [66]:
sgd=SGDRegressor(learning_rate=0.2,epochs=100)

In [67]:
sgd.fit(X_train,y_train)

coef=[  23.33334028    3.56997163  223.24677173  124.90749267  -10.81830948
  -15.69120144 -163.26008794  146.54029799  176.72034939  151.27857176],intercept=191.1154890250849
coef=[   6.74217454  -49.78175072  328.80739284  198.60512802  -14.59387865
  -40.84564447 -180.33083049  154.59191153  250.82217911  165.16292059],intercept=186.07205817856115
coef=[  17.54290041  -94.50296868  438.6958244   284.0257288   -33.5669727
  -61.18411463 -210.15122191  150.84161623  286.9429224   174.31683763],intercept=132.48482564186614
coef=[  -3.46022012  -95.55547573  463.03750419  286.51563284  -36.0801185
  -45.99754391 -212.02889567  153.81496874  277.83263187  164.41237707],intercept=141.20873722765896
coef=[ -15.49195713  -96.22382597  482.34573043  311.00539819  -45.00058021
  -77.50080622 -200.56003679  156.73708774  321.54307492  160.94447916],intercept=123.50827400563841
coef=[ -30.19280844  -97.94835105  481.162074    317.09370654  -88.15885572
 -131.36167303 -202.57430327  141.6666128 

coef=[  -1.1591755  -206.07003326  559.61922994  346.63183082 -245.1057645
  -48.35456361 -156.66455409  202.7300527   484.13921575   53.30078577],intercept=176.88331842721075
coef=[  13.54368584 -213.61048341  563.69857423  323.47365808 -270.6376247
  -61.53547089 -172.23548226  202.61884936  466.2587432    84.25121884],intercept=133.96107834716102
coef=[  -1.66919306 -210.87740136  554.12721798  331.17038487 -237.04354628
  -31.75687241 -158.25452703  205.68718397  482.20067963   77.66123905],intercept=165.9845040090662
coef=[  14.45826721 -179.28853651  572.56196109  349.28165535 -247.51588942
  -32.8008485  -140.84342367  202.11474795  470.05295381  115.66646192],intercept=159.63243656354052
coef=[   3.38471054 -153.34333616  558.41990295  349.38663091 -253.90157087
  -34.86145427 -143.03707827  206.64992603  471.05057824  112.57588985],intercept=225.45280958425067
coef=[   8.85737422 -229.30780654  540.59243799  366.57039825 -243.15375127
  -20.04120424 -114.08664371  190.2002894 

In [68]:
y_pred=sgd.predict(X_test)

In [69]:
print(r2_score(y_test,y_pred))

0.4142682352235286


In [70]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(X_train,)